# docker-compose.yml
# version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    
    # ***** LÍNEA MODIFICADA *****
    # Ya no definimos el 'command' aquí, porque el Dockerfile 
    # se encargará de ejecutar entrypoint.sh
    
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis