# docker-compose.yml
# version: '3.8'

services:
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    
    # ***** LÍNEA MODIFICADA *****
    # Ya no definimos el 'command' aquí, porque el Dockerfile 
    # se encargará de ejecutar entrypoint.sh
    
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

   # 👇 Nuevo servicio: Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # descomenta después si usas HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: unless-stopped

  worker:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped