# Este archivo le dice a Render cómo construir y desplegar tu aplicación.
# Se basa directamente en tu archivo docker-compose.yml.
services:
  # 1. El servicio de Redis
  # Render ofrece Redis como un servicio gestionado, lo cual es más robusto.
  - type: redis
    name: equilibra-redis
    plan: free # Elige el plan gratuito para empezar
    # --- LÍNEA AÑADIDA ---
    # Esto permite que tus otros servicios de Render (web y worker) se conecten a Redis.
    # 0.0.0.0/0 en este contexto es seguro y se refiere a la red interna de Render.
    ipAllowList: [] # Permitir acceso desde cualquier servicio dentro de tu cuenta de Render

  # 2. El servicio de la aplicación web (Gunicorn)
  - type: web
    name: equilibra-web
    plan: free # El plan gratuito puede ser lento al arrancar, pero es funcional
    env: docker # Le decimos a Render que use nuestro Dockerfile
    autoDeploy: true # Se redespliega automáticamente con cada 'git push' a la rama main
    healthCheckPath: /login # Render verificará esta ruta para saber si la app está sana
    envVars:
      # Render gestiona las variables de entorno de forma segura en su dashboard.
      # Aquí solo le decimos que necesita la URL de Redis.
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: equilibra-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: equilibra-redis
          property: connectionString
      # ¡IMPORTANTE! Debes añadir el resto de tus variables de entorno
      # (SECRET_KEY, GEMINI_API_KEY, MAIL_*, etc.) en el dashboard de Render.

  # 3. El servicio del trabajador Celery
  - type: worker
    name: equilibra-worker
    plan: free
    env: docker
    autoDeploy: true
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: equilibra-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: equilibra-redis
          property: connectionString
      # El worker también necesita acceso a todas las demás variables de entorno.
```

**Nota sobre `ipAllowList: []`:** Aunque `0.0.0.0/0` normalmente significa "abierto a todo internet", en el contexto de la `ipAllowList` de Render para servicios privados, una lista vacía `[]` se interpreta como "accesible por otros servicios dentro de la misma cuenta", lo cual es exactamente lo que necesitamos y es seguro.

#### **Paso 2: Sube el Cambio a GitHub**

Ahora que has corregido el archivo, necesitas subirlo a tu repositorio para que Render pueda verlo.

1.  Abre tu terminal en la raíz del proyecto.
2.  Ejecuta los siguientes comandos de Git:
    ```bash
    git add render.yaml
    git commit -m "fix: Add IP allow list for Redis on Render"
    git push origin main
    

