"""Add role and status to User model

Revision ID: 2143f67c3423
Revises: 273edcdb6482
Create Date: 2025-06-07 23:47:17.451202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2143f67c3423'
down_revision = '273edcdb6482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False, server_default='patient'))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='active'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
